### ISSUE TITLE
Problem enabling star rating on google SERP

### ISSUE THREAD

**Issue by sadaffathali** [jdmagic21/cc-testimonials#1]
I work on a PHP website that uses no CMS such as WP. After inserting the Schema, the data structure test is positive. However, Google does not seem to show star rating snippet. I need to figure out a way to fix this since it has a huge effect on the website's overall SEO.

**Comment by codedcontainer** [comment]
@sadaffathali  Thank you for your comment! I have just updated the plugin with support for schema.org. I also included a max star counter and will only show stars if the rating is greater than 0.  I am going to close this ticket but if you have any problems be sure to create another issue.
